project: 
  type: website
  render:
    - "*.{qmd,m,py,ipynb}"
  
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default

website: 
  page-navigation: true
  title: "ASDC Data and User Services" 
  site-url: "https://nasa.github.io/ASDC_Data_and_User_Services/" 
  repo-url: https://github.com/nasa/ASDC_Data_and_User_Services
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "Atmospheric Science Data Center"
    
  sidebar:
    logo: "https://archive.ph/Np7yS/b8ad2ce6e0dc2019a56b06908e6a31d0dbb1d544.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://eosweb.larc.nasa.gov/
        text: "NASA ASDC Website"
      - icon: github
        href: https://github.com/nasa/ASDC_Data_and_User_Services
        text: "ASDC Data and User Services GitHub Repository"        

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Mission-specific guidance"
        href: index.qmd
        contents:
        - section: "**CALIPSO** (Cloud-Aerosol Lidar and Infrared Pathfinder Satellite Observations)"
          contents:
            - section: "How do I..."
              contents:
              - text: Plot ozone number densities
                href: CALIPSO/how_to_plot_ozone_number_densities.ipynb
        - section: "**DSCOVR** (Deep Space Climate Observatory)"
          contents:
          - section: "How do I..."
            contents:
            - text: Explore aerosol data from EPIC and EPA-AQS
              href: DSCOVR/how_to_explore_aerosol_data_from_EPIC_and_EPA-AQS.ipynb
            - text: Compare TEMPO and DSCOVR aerosol data (spatially)
              href: DSCOVR/how_to_compare_spatially_TEMPO_with_DSCOVR_uvai.ipynb
            - text: Compare TEMPO, DSCOVR, and AERONET aerosol data
              href: DSCOVR/how_to_compare_TEMPO_with_DSCOVR_and_AERONET_uvai.ipynb
            - text: Compute daily averages of EPIC Level-2 total ozone (TO3) using OPeNDAP
              href: DSCOVR/how_to_compute_daily_averages_of_DSCOVR_EPIC_Level-2_TO3_total_ozone_using_OPeNDAP.ipynb
            - text: Compute daily averages of EPIC Level-4 TrO3 using OPeNDAP
              href: DSCOVR/how_to_compute_daily_averages_of_DSCOVR_EPIC_Level-4_TrO3_Using_OPeNDAP.ipynb
            - text: Plot Level-2 ozone product parameters
              href: DSCOVR/how_to_plot_ozone_product_parameters.ipynb
        - section: "**MAIA** (Multi-Angle Imager for Aerosols)"
          contents:
          - section: "How do I..."
            contents:
            - text: Plot map using a local file
              href: MAIA/how_to_plot_map_of_MAIA_data_using_a_local_file.ipynb
            - text: Convert data from NetCDF to CSV format
              href: MAIA/how_to_convert_data_from_netCDF_to_csv_format.ipynb
        - section: "**MISR** (Multi-Angle Imaging SpectroRadiometer)"
          contents:
          - section: "How do I..."
            contents:
            - text: Calculate and visualize Aerosol Optical Depths (AOD)
              href: MISR/how_to_compute_and_visualize_aerosol_optical_depths.ipynb
        - section: "**MOPITT** (Measurements Of Pollution In The Troposphere)"
          contents:
          - section: "How do I..."
            contents:
            - text: Plot carbon monoxide mixing ratios
              href: MOPITT/how_to_plot_carbon_monoxide_mixing_ratio.ipynb
        - section: "**PREFIRE** (Polar Radiant Energy in the Far-InfraRed Experiment)"
          contents:
          - section: "How do I..."
            contents:
            - text: Generate tiled images using HyBIG
              href: PREFIRE/how_to_generate_tiled_images_for_PREFIRE_using_HyBIG.ipynb
        - section: "**TEMPO** (Tropospheric Emissions: Monitoring of Pollution)"
          contents:
          - section: "How do I..."
            contents:
            - text: Examine data details using `earthaccess` and `harmony-py`
              href: TEMPO/how_to_examine_TEMPO_data_using_earthaccess_and_harmony-py.ipynb
            - text: Visualize data using `harmony-py`
              href: TEMPO/how_to_visualize_TEMPO_data_using_harmony-py.ipynb
        - section: "**TOLNet** (Tropospheric Ozone Lidar Network)"
          contents:
          - section: "Tutorials"
            contents:
            - text: The TOLNet API - with examples of plotting and using GEOS-CF
              href: TOLNet/tutorial_for_TOLNet_API_with_examples_of_plotting_and_GEOS-CF.ipynb
      - text: Additional reference code (not notebooks)
        href: additional_code_references.qmd
      - learning-more.qmd


format:
  html:
    theme:
      light: cosmo # from https://quarto.org/docs/output-formats/html-themes.html
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


# filters:
#   - include-files.lua
#   - quarto
