project: 
  type: website
  
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default

website: 
  page-navigation: true
  title: "ASDC Data and User Services" 
  site-url: "https://nasa.github.io/ASDC_Data_and_User_Services/" 
  repo-url: https://github.com/nasa/ASDC_Data_and_User_Services
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "Atmospheric Science Data Center"
    
  sidebar:
    # logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://eosweb.larc.nasa.gov/
        text: "NASA ASDC"
      - icon: github
        href: https://github.com/nasa/ASDC_Data_and_User_Services
        text: "ASDC Data and User Services"        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: README.md
        text: Welcome
      - section: missions_index.qmd
        contents: 
          - text: "DSCOVR UVAI Exploration"
            href: DSCOVR/dscovr_uvai_exploration.ipynb
          # - text: "Earthdata Cloud Clinic"
          #   href: tutorials/Earthdata-cloud-clinic.ipynb
      # - learning-more.qmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


# filters:
#   - include-files.lua
#   - quarto
