name: "Quarto Render and Publish to Pages"

on:
  push:
    branches: [ main, quarto/**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

  # we now use semantic versioning for the action
  # you could also use `...@v1.4.1`
  # or the git sha directly `...@5d5dbebd87f7b9358c403c7a66651fa92b310105`
      - name: "Install Conda environment"
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >- # beware the >- instead of |, we don't split on newlines but on spaces
            python=3.10
            numpy
          # now called cache-environment
          cache-environment: true

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
